apiVersion: v1
kind: Secret
metadata:
  name: rails
type: Opaque
data:
  secret-key-base: NTBkYWUxNmQ3ZDE0MDNlMTc1Y2ViMjQ2MTYwNWI1MjdjZjg3YTViMTg0Nzk3NDA1MDgzOTVjYjNmMTk0N2IxMmI2M2JhZDA0OWQ3ZDE1NDVhZjRkY2FmYTE3YTMyOWJlNGQyOWMxOGJkNjNiNDIxNTE1ZTM3YjQzZWE0M2RmNjQ=
