amazon:
  service: S3
  access_key_id: <%= ENV["S3_ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["S3_SECRET_KEY"] %>
  bucket: <%= ENV["S3_BUCKET_NAME"] %>
  region: <%= ENV["S3_REGION"] %>
  endpoint: <%= ENV["S3_ENDPOINT"] %>
